/**
 * Canonical template v1 for the preparation plan (WEBAPP_SPEC.md section 11).
 * Generated data is validated with Zod at the template boundary; the database
 * artifact (supabase/templates/plan_v1.json via
 * supabase/migrations/20260829020000_template_artifact.sql) is generated from
 * this module by scripts/generate-template-artifacts.mjs. CI proves both
 * artifacts share the same stable keys and content digest.
 *
 * Source of truth: docs/PLAN_TASK_MAPPING.md (reconciled to exactly 196 h).
 */

import { z } from "zod";

export const PLAN_WINDOW_START = "2026-08-31" as const;
export const PLAN_WINDOW_END = "2026-12-06" as const;
export const TEMPLATE_VERSION = 1 as const;

export const templateWeekSchema = z.object({
  week: z.number().int().min(1).max(14),
  title: z.string().min(1),
  start: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  end: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  phase: z.string().min(1),
  exitCheck: z.string().min(1),
});

export const ROLE_KEYS = ["data_eval", "agent_env", "post_training"] as const;
export type RoleKey = (typeof ROLE_KEYS)[number];

export const templateTaskSchema = z.object({
  key: z
    .string()
    .regex(/^w\d{2}-(mon|tue|wed|thu|fri|sat|sun)(-review)?$/, "routine key")
    .or(z.string().regex(/^pt-w\d{1,2}-[a-z0-9-]+$/, "post-training key")),
  week: z.number().int().min(1).max(14),
  day: z.enum(["mon", "tue", "wed", "thu", "fri", "sat", "sun"]),
  category: z.enum(["deep_work", "practice", "application", "review"]),
  minutes: z.number().int().positive(),
  title: z.string().min(1),
  roles: z.array(z.enum(ROLE_KEYS)).min(1),
  project: z.enum(["evalops", "rollout_lab", "post_training_lab"]).optional(),
  fixedDeadline: z.boolean().default(false),
  optionalTrack: z.boolean().default(false),
  swapGroup: z.literal("post_training").optional(),
});

export const milestoneSchema = z.object({
  key: z.string().regex(/^p[123]-m\d$/),
  title: z.string().min(1),
  acceptance: z.string().min(1),
  targetDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  isCompletionGate: z.boolean(),
  sortOrder: z.number().int().min(0),
});

export const projectSchema = z.object({
  key: z.enum(["evalops", "rollout_lab", "post_training_lab"]),
  name: z.string().min(1),
  targetRoles: z.array(z.enum(ROLE_KEYS)).min(1),
  budgetMinutes: z.number().int().positive(),
  state: z.enum(["locked", "active", "completed", "at_risk"]),
  purpose: z.string().min(1),
  milestones: z.array(milestoneSchema).min(1),
});

export const gateSchema = z.object({
  role: z.enum(ROLE_KEYS),
  key: z.string().min(1),
  title: z.string().min(1),
});

export const templateV1Schema = z.object({
  version: z.literal(1),
  windowStart: z.string(),
  windowEnd: z.string(),
  weeks: z.array(templateWeekSchema).length(14),
  tasks: z.array(templateTaskSchema),
  projects: z.array(projectSchema).length(3),
  gates: z.array(gateSchema),
});

export type TemplateWeek = z.infer<typeof templateWeekSchema>;
export type TemplateTask = z.infer<typeof templateTaskSchema>;
export type TemplateTaskInput = z.input<typeof templateTaskSchema>;
export type TemplateProject = z.infer<typeof projectSchema>;
export type TemplateGate = z.infer<typeof gateSchema>;
export type TemplateV1 = z.infer<typeof templateV1Schema>;

const RAW_WEEKS: TemplateWeek[] = [
  {
    week: 1,
    title: "Positioning and baselines",
    start: "2026-08-31",
    end: "2026-09-06",
    phase: "Application sprint",
    exitCheck:
      "Data/Eval application submitted; Agentic resume draft; evidence sheets; project design; coding baseline; no unsupported claims",
  },
  {
    week: 2,
    title: "Application sprint",
    start: "2026-09-07",
    end: "2026-09-13",
    phase: "Application sprint",
    exitCheck: "Both applications submitted; application copy archived; recruiter screen ready",
  },
  {
    week: 3,
    title: "Evaluation statistics",
    start: "2026-09-14",
    end: "2026-09-20",
    phase: "Portfolio build",
    exitCheck: "Metrics tested on synthetic fixtures; explain why each metric can mislead",
  },
  {
    week: 4,
    title: "Agent environments and optional-role decision",
    start: "2026-09-21",
    end: "2026-09-27",
    phase: "Portfolio build",
    exitCheck:
      "End-to-end run works; every failure category has an example; Post-Training decision recorded",
  },
  {
    week: 5,
    title: "Judge and annotation calibration",
    start: "2026-09-28",
    end: "2026-10-04",
    phase: "Portfolio build",
    exitCheck: "Judge reliability is quantified rather than asserted",
  },
  {
    week: 6,
    title: "Production-quality release",
    start: "2026-10-05",
    end: "2026-10-11",
    phase: "Portfolio build",
    exitCheck: "A fresh clone can run the smoke suite; feedback issues are tracked publicly",
  },
  {
    week: 7,
    title: "LLM systems foundations",
    start: "2026-10-12",
    end: "2026-10-18",
    phase: "Systems depth",
    exitCheck: "Answer core concepts on a whiteboard and connect them to your vLLM results",
  },
  {
    week: 8,
    title: "Distributed training",
    start: "2026-10-19",
    end: "2026-10-25",
    phase: "Systems depth",
    exitCheck:
      "Choose a parallelism plan for a specified model/cluster and estimate memory with explicit assumptions",
  },
  {
    week: 9,
    title: "Post-training depth",
    start: "2026-10-26",
    end: "2026-11-01",
    phase: "Evidence and report",
    exitCheck:
      "Defend why RL-Text2Vis used its reward/evaluation design and what you would change at scale",
  },
  {
    week: 10,
    title: "Product evaluation and agent reliability",
    start: "2026-11-02",
    end: "2026-11-08",
    phase: "Evidence and report",
    exitCheck: "Recommendations connect metrics to a product or model decision",
  },
  {
    week: 11,
    title: "Experiment report",
    start: "2026-11-09",
    end: "2026-11-15",
    phase: "Evidence and report",
    exitCheck: "Another ML engineer can audit the claim from configs and result artifacts",
  },
  {
    week: 12,
    title: "Full interview loop I",
    start: "2026-11-16",
    end: "2026-11-22",
    phase: "Interview loops",
    exitCheck: "No mock dimension below 3/5; every answer begins with a direct thesis",
  },
  {
    week: 13,
    title: "Targeted repair",
    start: "2026-11-23",
    end: "2026-11-29",
    phase: "Interview loops",
    exitCheck: "Two consecutive mocks meet all readiness thresholds",
  },
  {
    week: 14,
    title: "Full interview loop II and maintenance mode",
    start: "2026-11-30",
    end: "2026-12-06",
    phase: "Interview loops",
    exitCheck: "All readiness gates pass or have a written mitigation",
  },
];

const DAY_OFFSET: Record<TemplateTask["day"], number> = {
  mon: 0,
  tue: 1,
  wed: 2,
  thu: 3,
  fri: 4,
  sat: 5,
  sun: 6,
};

function isoDate(weekStart: string, day: TemplateTask["day"]): string {
  const start = new Date(`${weekStart}T12:00:00Z`);
  start.setUTCDate(start.getUTCDate() + DAY_OFFSET[day]);
  return start.toISOString().slice(0, 10);
}

const RAW_TASKS: TemplateTaskInput[] = [
  {
    key: "w01-mon",
    week: 1,
    day: "mon",
    category: "practice",
    minutes: 120,
    title: "Timed Python coding baseline and mistake log",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w01-tue",
    week: 1,
    day: "tue",
    category: "deep_work",
    minutes: 120,
    title: "Agent-eval design baseline and core concepts",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w01-wed",
    week: 1,
    day: "wed",
    category: "application",
    minutes: 120,
    title: "Requirement/evidence/gap rows for both role descriptions",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w01-thu",
    week: 1,
    day: "thu",
    category: "deep_work",
    minutes: 120,
    title: "Specify Projects 1-2 scope, architecture, and experiment plans",
    roles: ["data_eval", "agent_env"],
    project: "evalops",
  },
  {
    key: "w01-fri",
    week: 1,
    day: "fri",
    category: "application",
    minutes: 60,
    title: "Draft Data/Evaluation resume with focused summary",
    roles: ["data_eval"],
  },
  {
    key: "w01-sat",
    week: 1,
    day: "sat",
    category: "application",
    minutes: 180,
    title: "Recover six CV metrics; record intro and deep dives; identify contacts; arrange review",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w01-sun",
    week: 1,
    day: "sun",
    category: "application",
    minutes: 90,
    title: "Submit Data Analysis and Evaluation application",
    roles: ["data_eval"],
    fixedDeadline: true,
  },
  {
    key: "w01-sun-review",
    week: 1,
    day: "sun",
    category: "review",
    minutes: 30,
    title: "Weekly scorecard and exit check",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w02-mon",
    week: 2,
    day: "mon",
    category: "practice",
    minutes: 120,
    title: "Two timed coding problems, fully reviewed",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w02-tue",
    week: 2,
    day: "tue",
    category: "application",
    minutes: 120,
    title: "Submit Agentic Environments application",
    roles: ["agent_env"],
    fixedDeadline: true,
  },
  {
    key: "w02-wed",
    week: 2,
    day: "wed",
    category: "deep_work",
    minutes: 120,
    title: "Project 1: task, environment, trajectory schemas; verifier skeleton",
    roles: ["data_eval", "agent_env"],
    project: "evalops",
  },
  {
    key: "w02-thu",
    week: 2,
    day: "thu",
    category: "deep_work",
    minutes: 120,
    title: "Project 1: environment and trajectory implementation with tests",
    roles: ["data_eval", "agent_env"],
    project: "evalops",
  },
  {
    key: "w02-fri",
    week: 2,
    day: "fri",
    category: "application",
    minutes: 60,
    title: "Interview narratives 1-2: benchmark design; agent failure",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w02-sat",
    week: 2,
    day: "sat",
    category: "deep_work",
    minutes: 210,
    title: "Project 1 deep block: end-to-end smoke task to trajectory to verifier",
    roles: ["data_eval", "agent_env"],
    project: "evalops",
  },
  {
    key: "w02-sun",
    week: 2,
    day: "sun",
    category: "application",
    minutes: 60,
    title: "Interview narratives 3-4: inference optimization; disagreement story",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w02-sun-review",
    week: 2,
    day: "sun",
    category: "review",
    minutes: 30,
    title: "Weekly scorecard and exit check",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w03-mon",
    week: 3,
    day: "mon",
    category: "practice",
    minutes: 120,
    title: "Two timed coding problems, fully reviewed",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w03-tue",
    week: 3,
    day: "tue",
    category: "deep_work",
    minutes: 120,
    title: "Project 1: task metrics, stratified slices, bootstrap CIs, paired comparison",
    roles: ["data_eval", "agent_env"],
    project: "evalops",
  },
  {
    key: "w03-wed",
    week: 3,
    day: "wed",
    category: "deep_work",
    minutes: 120,
    title: "Evaluation statistics study: bias, leakage, power, calibration, agreement, tests",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w03-thu",
    week: 3,
    day: "thu",
    category: "deep_work",
    minutes: 120,
    title: "Project 1: human-labeling guide with edge cases and adjudication",
    roles: ["data_eval", "agent_env"],
    project: "evalops",
  },
  {
    key: "w03-fri",
    week: 3,
    day: "fri",
    category: "deep_work",
    minutes: 60,
    title: "Judge-bias paper notes: how each metric can mislead",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w03-sat",
    week: 3,
    day: "sat",
    category: "deep_work",
    minutes: 210,
    title: "Project 1: metrics on synthetic fixtures; provenance fields",
    roles: ["data_eval", "agent_env"],
    project: "evalops",
  },
  {
    key: "w03-sun",
    week: 3,
    day: "sun",
    category: "practice",
    minutes: 60,
    title: "Statistics mock",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w03-sun-review",
    week: 3,
    day: "sun",
    category: "review",
    minutes: 30,
    title: "Weekly scorecard and exit check",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w04-mon",
    week: 4,
    day: "mon",
    category: "practice",
    minutes: 120,
    title: "Two timed coding problems, fully reviewed",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w04-tue",
    week: 4,
    day: "tue",
    category: "deep_work",
    minutes: 120,
    title: "Project 1: implement two tool-use environments and trajectory logging",
    roles: ["data_eval", "agent_env"],
    project: "evalops",
  },
  {
    key: "w04-wed",
    week: 4,
    day: "wed",
    category: "deep_work",
    minutes: 120,
    title:
      "Project 1: inject failures: invalid args, retrieval, timeout, stale state, partial completion",
    roles: ["data_eval", "agent_env"],
    project: "evalops",
  },
  {
    key: "w04-thu",
    week: 4,
    day: "thu",
    category: "deep_work",
    minutes: 120,
    title: "Project 1: first baseline; manually inspect at least 20 trajectories",
    roles: ["data_eval", "agent_env"],
    project: "evalops",
  },
  {
    key: "w04-fri",
    week: 4,
    day: "fri",
    category: "application",
    minutes: 60,
    title: "Post-Training evidence honesty check; confirm Canada option for Agentic",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w04-sat",
    week: 4,
    day: "sat",
    category: "deep_work",
    minutes: 210,
    title: "Project 1: baseline fixes; verifier improvements; demo run",
    roles: ["data_eval", "agent_env"],
    project: "evalops",
  },
  {
    key: "w04-sun",
    week: 4,
    day: "sun",
    category: "practice",
    minutes: 60,
    title: "Enterprise-agent eval design mock",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w04-sun-review",
    week: 4,
    day: "sun",
    category: "review",
    minutes: 30,
    title: "Weekly scorecard; record Post-Training go/no-go decision",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w05-mon",
    week: 5,
    day: "mon",
    category: "practice",
    minutes: 120,
    title: "Two timed coding problems, fully reviewed",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w05-tue",
    week: 5,
    day: "tue",
    category: "deep_work",
    minutes: 120,
    title: "Project 1: pilot annotation instructions; run three-annotator study",
    roles: ["data_eval", "agent_env"],
    project: "evalops",
  },
  {
    key: "w05-wed",
    week: 5,
    day: "wed",
    category: "deep_work",
    minutes: 120,
    title: "Measure human-human and human-judge agreement; revise rubric once; report pre/post",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w05-thu",
    week: 5,
    day: "thu",
    category: "deep_work",
    minutes: 120,
    title: "Project 1: rubric/model verifier; data versioning; deterministic fixtures",
    roles: ["data_eval", "agent_env"],
    project: "evalops",
  },
  {
    key: "w05-fri",
    week: 5,
    day: "fri",
    category: "application",
    minutes: 60,
    title: "Two or three genuine professional conversations; thank-you notes",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w05-sat",
    week: 5,
    day: "sat",
    category: "deep_work",
    minutes: 210,
    title: "Project 2: sequential/Ray runners; idempotent task IDs; checkpoint/resume design",
    roles: ["data_eval", "agent_env"],
    project: "rollout_lab",
  },
  {
    key: "w05-sun",
    week: 5,
    day: "sun",
    category: "practice",
    minutes: 60,
    title: "Behavioral mock",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w05-sun-review",
    week: 5,
    day: "sun",
    category: "review",
    minutes: 30,
    title: "Weekly scorecard and exit check",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w06-mon",
    week: 6,
    day: "mon",
    category: "practice",
    minutes: 120,
    title: "Two timed coding problems, fully reviewed",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w06-tue",
    week: 6,
    day: "tue",
    category: "deep_work",
    minutes: 120,
    title: "Project 1: unit/integration tests, typing, linting, CI",
    roles: ["data_eval", "agent_env"],
    project: "evalops",
  },
  {
    key: "w06-wed",
    week: 6,
    day: "wed",
    category: "deep_work",
    minutes: 120,
    title:
      "Project 1: structured logs, failure recovery, cost/latency reporting; credential-free smoke test",
    roles: ["data_eval", "agent_env"],
    project: "evalops",
  },
  {
    key: "w06-thu",
    week: 6,
    day: "thu",
    category: "deep_work",
    minutes: 120,
    title: "Project 1: two-page design doc and results chart",
    roles: ["data_eval", "agent_env"],
    project: "evalops",
  },
  {
    key: "w06-fri",
    week: 6,
    day: "fri",
    category: "application",
    minutes: 60,
    title: "Ask three domain reviewers for technical criticism; track issues publicly",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w06-sat",
    week: 6,
    day: "sat",
    category: "deep_work",
    minutes: 210,
    title: "Publish Project 1 v0.1 with short demo; tag release",
    roles: ["data_eval", "agent_env"],
    project: "evalops",
  },
  {
    key: "w06-sun",
    week: 6,
    day: "sun",
    category: "practice",
    minutes: 60,
    title: "Recorded Project 1 design deep-dive with rubric self-score",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w06-sun-review",
    week: 6,
    day: "sun",
    category: "review",
    minutes: 30,
    title: "Weekly scorecard; Project 1 completion-gate self-check",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w07-mon",
    week: 7,
    day: "mon",
    category: "practice",
    minutes: 120,
    title: "Two timed coding problems, fully reviewed",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w07-tue",
    week: 7,
    day: "tue",
    category: "deep_work",
    minutes: 120,
    title: "Derive attention, causal masking, cross-entropy, normalization, KV-cache behavior",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w07-wed",
    week: 7,
    day: "wed",
    category: "deep_work",
    minutes: 120,
    title:
      "Tokenization, positional methods, batching, quantization, speculative decoding, memory vs compute",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w07-thu",
    week: 7,
    day: "thu",
    category: "deep_work",
    minutes: 120,
    title: "Project 2: load tests at three concurrency levels and two batching settings",
    roles: ["data_eval", "agent_env"],
    project: "rollout_lab",
  },
  {
    key: "w07-fri",
    week: 7,
    day: "fri",
    category: "deep_work",
    minutes: 60,
    title: "Connect vLLM results to throughput/latency explanations",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w07-sat",
    week: 7,
    day: "sat",
    category: "deep_work",
    minutes: 210,
    title: "Project 2: profile inference/rollout workload; record bottleneck evidence",
    roles: ["data_eval", "agent_env"],
    project: "rollout_lab",
  },
  {
    key: "w07-sun",
    week: 7,
    day: "sun",
    category: "practice",
    minutes: 60,
    title: "Inference-system design mock",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w07-sun-review",
    week: 7,
    day: "sun",
    category: "review",
    minutes: 30,
    title: "Weekly scorecard and exit check",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w08-mon",
    week: 8,
    day: "mon",
    category: "practice",
    minutes: 120,
    title: "Two timed coding problems, fully reviewed",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w08-tue",
    week: 8,
    day: "tue",
    category: "deep_work",
    minutes: 120,
    title:
      "DDP, FSDP/ZeRO, tensor/pipeline parallelism, checkpointing, accumulation, mixed precision, all-reduce",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w08-wed",
    week: 8,
    day: "wed",
    category: "deep_work",
    minutes: 120,
    title:
      "Profiling workflow: GPU utilization, stalls, communication, fragmentation, OOM diagnosis",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w08-thu",
    week: 8,
    day: "thu",
    category: "deep_work",
    minutes: 120,
    title: "Project 2: single vs two-process DDP correctness; failure-resume without duplicates",
    roles: ["data_eval", "agent_env"],
    project: "rollout_lab",
  },
  {
    key: "w08-fri",
    week: 8,
    day: "fri",
    category: "deep_work",
    minutes: 60,
    title: "Project 2: container and distributed data partitioning tests",
    roles: ["data_eval", "agent_env"],
    project: "rollout_lab",
  },
  {
    key: "w08-sat",
    week: 8,
    day: "sat",
    category: "deep_work",
    minutes: 210,
    title:
      "Project 2: profiler analysis; benchmark report with tokens/s, memory, scaling efficiency; demo",
    roles: ["data_eval", "agent_env"],
    project: "rollout_lab",
  },
  {
    key: "w08-sun",
    week: 8,
    day: "sun",
    category: "practice",
    minutes: 60,
    title: "Training-system design mock",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w08-sun-review",
    week: 8,
    day: "sun",
    category: "review",
    minutes: 30,
    title: "Weekly scorecard; Project 2 completion-gate self-check",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w09-mon",
    week: 9,
    day: "mon",
    category: "practice",
    minutes: 120,
    title: "Two timed coding problems, fully reviewed",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w09-tue",
    week: 9,
    day: "tue",
    category: "deep_work",
    minutes: 120,
    title: "Re-derive SFT, reward modeling, DPO, PPO-style RLHF, GRPO, RLVR objectives",
    roles: ["data_eval", "agent_env"],
    swapGroup: "post_training",
  },
  {
    key: "w09-wed",
    week: 9,
    day: "wed",
    category: "deep_work",
    minutes: 120,
    title:
      "Reward hacking, KL control, on/off-policy, credit assignment, verifier design, contamination",
    roles: ["data_eval", "agent_env"],
    swapGroup: "post_training",
  },
  {
    key: "w09-thu",
    week: 9,
    day: "thu",
    category: "deep_work",
    minutes: 120,
    title: "Execute the Week-4 Post-Training decision: Project 3 setup or Agentic gate repair",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w09-fri",
    week: 9,
    day: "fri",
    category: "application",
    minutes: 60,
    title: "Defend the RL-Text2Vis reward/evaluation design; draft scale changes",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w09-sat",
    week: 9,
    day: "sat",
    category: "deep_work",
    minutes: 210,
    title: "Project 1 ablation-matrix prep, or first Project 3 experiment per decision",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w09-sun",
    week: 9,
    day: "sun",
    category: "practice",
    minutes: 60,
    title: "Post-training design mock",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w09-sun-review",
    week: 9,
    day: "sun",
    category: "review",
    minutes: 30,
    title: "Weekly scorecard and exit check",
    roles: ["data_eval", "agent_env"],
    swapGroup: "post_training",
  },
  {
    key: "w10-mon",
    week: 10,
    day: "mon",
    category: "practice",
    minutes: 120,
    title: "Two timed coding problems, fully reviewed",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w10-tue",
    week: 10,
    day: "tue",
    category: "deep_work",
    minutes: 120,
    title: "Convert three observed failures into regression tasks; no new environments",
    roles: ["data_eval", "agent_env"],
    project: "evalops",
  },
  {
    key: "w10-wed",
    week: 10,
    day: "wed",
    category: "deep_work",
    minutes: 120,
    title:
      "Privacy-preserving telemetry, consent, PII, retention, access control, auditability, prompt injection, tool authorization",
    roles: ["data_eval", "agent_env"],
    swapGroup: "post_training",
  },
  {
    key: "w10-thu",
    week: 10,
    day: "thu",
    category: "deep_work",
    minutes: 120,
    title:
      "Turn five ambiguous product complaints into hypotheses, slices, tasks, rubrics, thresholds",
    roles: ["data_eval", "agent_env"],
    swapGroup: "post_training",
  },
  {
    key: "w10-fri",
    week: 10,
    day: "fri",
    category: "application",
    minutes: 60,
    title: "Update resumes and evidence sheets with Project 2 evidence",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w10-sat",
    week: 10,
    day: "sat",
    category: "deep_work",
    minutes: 210,
    title: "Regression suite wired into CI; verify thresholds; case write-up",
    roles: ["data_eval", "agent_env"],
    project: "evalops",
  },
  {
    key: "w10-sun",
    week: 10,
    day: "sun",
    category: "practice",
    minutes: 60,
    title: "Sixty-minute case: prove improvement without hiding regressions",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w10-sun-review",
    week: 10,
    day: "sun",
    category: "review",
    minutes: 30,
    title: "Weekly scorecard and exit check",
    roles: ["data_eval", "agent_env"],
    swapGroup: "post_training",
  },
  {
    key: "w11-mon",
    week: 11,
    day: "mon",
    category: "practice",
    minutes: 120,
    title: "Coding mock 1: timed, recorded, scored",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w11-tue",
    week: 11,
    day: "tue",
    category: "deep_work",
    minutes: 120,
    title: "Run the Project 1 baseline/ablation matrix",
    roles: ["data_eval", "agent_env"],
    project: "evalops",
  },
  {
    key: "w11-wed",
    week: 11,
    day: "wed",
    category: "practice",
    minutes: 120,
    title: "Coding mock 2: timed, recorded, scored",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w11-thu",
    week: 11,
    day: "thu",
    category: "deep_work",
    minutes: 120,
    title:
      "Finalize Project 2 profiling comparison; report uncertainty, cost, latency, disagreement",
    roles: ["data_eval", "agent_env"],
    project: "rollout_lab",
  },
  {
    key: "w11-fri",
    week: 11,
    day: "fri",
    category: "deep_work",
    minutes: 60,
    title: "Write the technical report and executive summary (draft)",
    roles: ["data_eval", "agent_env"],
    project: "evalops",
  },
  {
    key: "w11-sat",
    week: 11,
    day: "sat",
    category: "deep_work",
    minutes: 210,
    title: "Finish the report: auditable from configs and result artifacts",
    roles: ["data_eval", "agent_env"],
    project: "evalops",
  },
  {
    key: "w11-sun",
    week: 11,
    day: "sun",
    category: "practice",
    minutes: 60,
    title: "Research deep-dive mock",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w11-sun-review",
    week: 11,
    day: "sun",
    category: "review",
    minutes: 30,
    title: "Weekly scorecard and exit check",
    roles: ["data_eval", "agent_env"],
    swapGroup: "post_training",
  },
  {
    key: "w12-mon",
    week: 12,
    day: "mon",
    category: "practice",
    minutes: 120,
    title: "Live-coding mock with scoring",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w12-tue",
    week: 12,
    day: "tue",
    category: "practice",
    minutes: 120,
    title: "ML fundamentals mock with scoring",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w12-wed",
    week: 12,
    day: "wed",
    category: "practice",
    minutes: 120,
    title: "ML system-design mock with scoring",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w12-thu",
    week: 12,
    day: "thu",
    category: "practice",
    minutes: 120,
    title: "Project/behavioral mock with scoring",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w12-fri",
    week: 12,
    day: "fri",
    category: "application",
    minutes: 60,
    title: "Update both resumes and evidence sheets with the two public projects",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w12-sat",
    week: 12,
    day: "sat",
    category: "deep_work",
    minutes: 210,
    title:
      "Four-hour take-home simulation: tests, README, assumptions, analysis, clean final commit",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w12-sun-review",
    week: 12,
    day: "sun",
    category: "review",
    minutes: 90,
    title: "Score recordings; create top-five weakness list; weekly review",
    roles: ["data_eval", "agent_env"],
    swapGroup: "post_training",
  },
  {
    key: "w13-mon",
    week: 13,
    day: "mon",
    category: "practice",
    minutes: 120,
    title: "Coding mock with scoring",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w13-tue",
    week: 13,
    day: "tue",
    category: "deep_work",
    minutes: 120,
    title: "Deliberate practice on the two lowest mock dimensions (1)",
    roles: ["data_eval", "agent_env"],
    swapGroup: "post_training",
  },
  {
    key: "w13-wed",
    week: 13,
    day: "wed",
    category: "deep_work",
    minutes: 120,
    title: "Deliberate practice on the two lowest mock dimensions (2)",
    roles: ["data_eval", "agent_env"],
    swapGroup: "post_training",
  },
  {
    key: "w13-thu",
    week: 13,
    day: "thu",
    category: "practice",
    minutes: 120,
    title: "Role-specific system-design mock 1",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w13-fri",
    week: 13,
    day: "fri",
    category: "application",
    minutes: 60,
    title: "Follow up with contacts using a concrete artifact; re-check current roles",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w13-sat",
    week: 13,
    day: "sat",
    category: "practice",
    minutes: 210,
    title: "Role-specific system-design mock 2; re-answer missed questions from scratch",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w13-sun-review",
    week: 13,
    day: "sun",
    category: "review",
    minutes: 90,
    title: "Exit check: two consecutive mocks meet all readiness thresholds",
    roles: ["data_eval", "agent_env"],
    swapGroup: "post_training",
  },
  {
    key: "w14-mon",
    week: 14,
    day: "mon",
    category: "practice",
    minutes: 120,
    title: "Simulated loop day 1: live coding and ML fundamentals",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w14-tue",
    week: 14,
    day: "tue",
    category: "practice",
    minutes: 120,
    title: "Simulated loop day 1: ML system design",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w14-wed",
    week: 14,
    day: "wed",
    category: "practice",
    minutes: 120,
    title: "Simulated loop day 2: project deep-dive and behavioral",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w14-thu",
    week: 14,
    day: "thu",
    category: "application",
    minutes: 120,
    title: "Finalize notes: metrics, equations, estimates, Cohere reasons, interviewer questions",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w14-fri",
    week: 14,
    day: "fri",
    category: "application",
    minutes: 60,
    title: "Review applications; decide follow-ups; set maintenance cadence",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "w14-sat",
    week: 14,
    day: "sat",
    category: "review",
    minutes: 210,
    title: "Final readiness-gate review: every gate passes or has a written mitigation",
    roles: ["data_eval", "agent_env"],
    swapGroup: "post_training",
  },
  {
    key: "w14-sun",
    week: 14,
    day: "sun",
    category: "review",
    minutes: 90,
    title: "Complete readiness matrix; confirm maintenance plan",
    roles: ["data_eval", "agent_env"],
  },
  {
    key: "pt-w9-scope",
    week: 9,
    day: "thu",
    category: "deep_work",
    minutes: 150,
    title:
      "Project 3: select narrow verifiable task and small open model; write reproducible config",
    roles: ["post_training"],
    project: "post_training_lab",
    optionalTrack: true,
  },
  {
    key: "pt-w9-sft",
    week: 9,
    day: "sat",
    category: "deep_work",
    minutes: 120,
    title: "Project 3: build a clean SFT baseline",
    roles: ["post_training"],
    project: "post_training_lab",
    optionalTrack: true,
  },
  {
    key: "pt-w10-preference",
    week: 10,
    day: "thu",
    category: "deep_work",
    minutes: 150,
    title: "Project 3: run one preference or verifiable-reward method (DPO or small GRPO)",
    roles: ["post_training"],
    project: "post_training_lab",
    optionalTrack: true,
  },
  {
    key: "pt-w10-rewards",
    week: 10,
    day: "sat",
    category: "deep_work",
    minutes: 120,
    title: "Project 3: reuse deterministic verifiers as rewards; log reward components, KL/entropy",
    roles: ["post_training"],
    project: "post_training_lab",
    optionalTrack: true,
  },
  {
    key: "pt-w11-ablation-setup",
    week: 11,
    day: "sun",
    category: "deep_work",
    minutes: 30,
    title: "Project 3: set up the reward-design ablation",
    roles: ["post_training"],
    project: "post_training_lab",
    optionalTrack: true,
  },
  {
    key: "pt-w12-ablation",
    week: 12,
    day: "sat",
    category: "deep_work",
    minutes: 90,
    title: "Project 3: complete the reward-design ablation; inspect reward hacking",
    roles: ["post_training"],
    project: "post_training_lab",
    optionalTrack: true,
  },
  {
    key: "pt-w13-eval",
    week: 13,
    day: "thu",
    category: "deep_work",
    minutes: 210,
    title:
      "Project 3: held-out evaluation vs prompting/SFT with confidence intervals and cost disclosure",
    roles: ["post_training"],
    project: "post_training_lab",
    optionalTrack: true,
  },
  {
    key: "pt-w13-docs",
    week: 13,
    day: "fri",
    category: "deep_work",
    minutes: 120,
    title: "Project 3: failure analysis and model card",
    roles: ["post_training"],
    project: "post_training_lab",
    optionalTrack: true,
  },
  {
    key: "pt-w14-final",
    week: 14,
    day: "sat",
    category: "deep_work",
    minutes: 210,
    title: "Project 3: reproducibility check; what would change at Cohere scale; final write-up",
    roles: ["post_training"],
    project: "post_training_lab",
    optionalTrack: true,
  },
];

const RAW_PROJECTS: TemplateProject[] = [
  {
    key: "evalops",
    name: "EvalOps for tool-using enterprise agents",
    targetRoles: ["data_eval", "agent_env"],
    budgetMinutes: 1950,
    state: "active",
    purpose:
      "Evaluation harness turning workflow requirements and observed agent failures into reproducible tasks, executable verifiers, statistical reports, and regression gates.",
    milestones: [
      {
        key: "p1-m1",
        title: "Skeleton",
        acceptance:
          "Task schema, environment interface, trajectory schema, deterministic verifier skeleton committed with tests",
        targetDate: "2026-09-13",
        isCompletionGate: false,
        sortOrder: 0,
      },
      {
        key: "p1-m2",
        title: "Environments and failures",
        acceptance:
          "Two environments, failure injection, first baseline, at least 20 trajectories manually inspected",
        targetDate: "2026-09-27",
        isCompletionGate: false,
        sortOrder: 1,
      },
      {
        key: "p1-m3",
        title: "Metrics and statistics",
        acceptance:
          "Task-level metrics, stratified slices, bootstrap CIs, paired comparison tested on synthetic fixtures",
        targetDate: "2026-09-20",
        isCompletionGate: false,
        sortOrder: 2,
      },
      {
        key: "p1-m4",
        title: "Annotation calibration",
        acceptance:
          "Pilot instructions, three-annotator study, agreement measured, rubric revised once, pre/post reported",
        targetDate: "2026-10-04",
        isCompletionGate: false,
        sortOrder: 3,
      },
      {
        key: "p1-m5",
        title: "Release v0.1",
        acceptance:
          "Tests/CI/typing/lint pass; credential-free smoke; design doc and demo published; three reviewer criticisms tracked; fresh clone runs the smoke suite",
        targetDate: "2026-10-11",
        isCompletionGate: true,
        sortOrder: 4,
      },
      {
        key: "p1-m6",
        title: "Regression gates",
        acceptance:
          "Three observed failures converted into regression tasks; thresholds enforced in CI",
        targetDate: "2026-11-08",
        isCompletionGate: false,
        sortOrder: 5,
      },
      {
        key: "p1-m7",
        title: "Technical report",
        acceptance:
          "Baseline/ablation matrix run; report includes baselines, ablations, uncertainty, failure taxonomy, limitations; auditable from configs and artifacts",
        targetDate: "2026-11-15",
        isCompletionGate: false,
        sortOrder: 6,
      },
    ],
  },
  {
    key: "rollout_lab",
    name: "Distributed training and rollout reliability lab",
    targetRoles: ["agent_env", "data_eval"],
    budgetMinutes: 1650,
    state: "active",
    purpose:
      "Production-style runner plus a deliberately small distributed-training workload: distributed correctness, rollout tooling, profiling, failure handling, clean engineering.",
    milestones: [
      {
        key: "p2-m1",
        title: "Runners and DDP design",
        acceptance:
          "Sequential and Ray runners, bounded concurrency, retries with jitter, idempotent task IDs, checkpoint/resume design",
        targetDate: "2026-10-04",
        isCompletionGate: false,
        sortOrder: 0,
      },
      {
        key: "p2-m2",
        title: "Load and profile",
        acceptance:
          "Rollout load test at three concurrency levels and two batching settings; torch.profiler evidence; throughput/latency explained from measurements",
        targetDate: "2026-10-18",
        isCompletionGate: false,
        sortOrder: 1,
      },
      {
        key: "p2-m3",
        title: "DDP and recovery",
        acceptance:
          "Single vs two-process DDP correctness; interrupted run resumes without duplicated samples; container, benchmark report, demo; profiling quantifies a real bottleneck with before/after",
        targetDate: "2026-10-25",
        isCompletionGate: true,
        sortOrder: 2,
      },
      {
        key: "p2-m4",
        title: "Comparison and post",
        acceptance:
          "Finalized profiling comparison; engineering post titled around a measured bottleneck",
        targetDate: "2026-11-15",
        isCompletionGate: false,
        sortOrder: 3,
      },
    ],
  },
  {
    key: "post_training_lab",
    name: "Verifier-guided post-training mini-lab",
    targetRoles: ["post_training"],
    budgetMinutes: 1200,
    state: "locked",
    purpose:
      "Optional: verifier-guided post-training on one narrow task with a genuinely small model, evaluated on held-out tasks.",
    milestones: [
      {
        key: "p3-m1",
        title: "SFT baseline",
        acceptance:
          "Narrow verifiable task and small open model selected; clean SFT baseline built",
        targetDate: "2026-11-01",
        isCompletionGate: false,
        sortOrder: 0,
      },
      {
        key: "p3-m2",
        title: "Method and rewards",
        acceptance:
          "One preference or verifiable-reward method run; deterministic verifiers as rewards; reward components and KL/entropy logged",
        targetDate: "2026-11-08",
        isCompletionGate: false,
        sortOrder: 1,
      },
      {
        key: "p3-m3",
        title: "Ablation",
        acceptance:
          "Reward-design ablation complete; reward hacking and generalization failures inspected",
        targetDate: "2026-11-22",
        isCompletionGate: false,
        sortOrder: 2,
      },
      {
        key: "p3-m4",
        title: "Report",
        acceptance:
          "Reproducible configs, training/eval curves, ablation table, held-out evaluation with confidence intervals, model card, what-would-change-at-scale section; positive result not required",
        targetDate: "2026-12-06",
        isCompletionGate: true,
        sortOrder: 3,
      },
    ],
  },
];

const RAW_GATES: TemplateGate[] = [
  {
    role: "data_eval",
    key: "resume",
    title:
      "Resume gate: reviewer finds evidence for 80% of core requirements; every metric defensible",
  },
  {
    role: "data_eval",
    key: "recruiter",
    title:
      "Recruiter gate: 90-second introduction, role motivation, location/authorization facts, six project summaries",
  },
  {
    role: "data_eval",
    key: "evaluation",
    title: "Evaluation gate: design an eval from an ambiguous complaint in 45 minutes",
  },
  {
    role: "data_eval",
    key: "research",
    title: "Research gate: explain three papers/projects through negative results and limitations",
  },
  {
    role: "data_eval",
    key: "project_1",
    title: "Project 1 gate: clean clone passes smoke test and CI; report complete",
  },
  {
    role: "data_eval",
    key: "behavioral",
    title: "Behavioral gate: six stories with decisions and measurable effects; two mocks at 4/5",
  },
  {
    role: "agent_env",
    key: "coding",
    title:
      "Coding gate: solve 8 of the latest 10 medium/practical Python tasks in 40 minutes with tests",
  },
  {
    role: "agent_env",
    key: "recruiter",
    title:
      "Recruiter gate: 90-second introduction, role motivation, location/authorization facts, six project summaries",
  },
  {
    role: "agent_env",
    key: "systems",
    title: "Systems gate: two consecutive 45-minute LLM system designs at 4/5",
  },
  {
    role: "agent_env",
    key: "project_2",
    title:
      "Project 2 gate: rollout and DDP smoke pass; interrupted runs resume; profiling quantifies a bottleneck",
  },
  {
    role: "agent_env",
    key: "behavioral",
    title: "Behavioral gate: six stories with decisions and measurable effects; two mocks at 4/5",
  },
  {
    role: "post_training",
    key: "pt_ownership",
    title:
      "Ownership evidence gate: real ownership of a training loop, reward/data design, ablation, debugging episode, measured outcome",
  },
  {
    role: "post_training",
    key: "pt_project3",
    title:
      "Project 3 held-out evidence gate: p3-m4 complete with held-out evidence; an SFT notebook alone is insufficient",
  },
];

/** Derive each task's exact scheduled date from its week and weekday. */
export function taskDate(task: TemplateTask): string {
  const week = RAW_WEEKS.find((w) => w.week === task.week);
  if (!week) throw new Error(`Unknown week ${task.week}`);
  return isoDate(week.start, task.day);
}

/**
 * The full validated template. Validated eagerly: invalid template data must
 * block deployment tests rather than fail at runtime (WEBAPP_SPEC.md section 16).
 */
export const TEMPLATE_V1: TemplateV1 = templateV1Schema.parse({
  version: 1,
  windowStart: PLAN_WINDOW_START,
  windowEnd: PLAN_WINDOW_END,
  weeks: RAW_WEEKS,
  tasks: RAW_TASKS,
  projects: RAW_PROJECTS,
  gates: RAW_GATES,
});

/** Stable task keys in canonical order. */
export const TEMPLATE_TASK_KEYS: string[] = TEMPLATE_V1.tasks.map((t) => t.key);

/** Deterministic content digest over the canonical template shape. */
export async function templateContentDigest(): Promise<string> {
  const canonical = {
    weeks: TEMPLATE_V1.weeks,
    tasks: TEMPLATE_V1.tasks.map((t) => ({ ...t, date: taskDate(t) })),
    projects: TEMPLATE_V1.projects,
    gates: TEMPLATE_V1.gates,
  };
  const bytes = new TextEncoder().encode(JSON.stringify(canonical));
  const hash = await crypto.subtle.digest("SHA-256", bytes);
  return Array.from(new Uint8Array(hash))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

/** Template tasks that the Post-Training unlock deactivates (the swap set). */
export const POST_TRAINING_SWAP_KEYS: string[] = TEMPLATE_V1.tasks
  .filter((t) => t.swapGroup === "post_training")
  .map((t) => t.key);

/** Optional Post-Training task keys and their total minutes (must equal 1,200). */
export const POST_TRAINING_TASK_KEYS: string[] = TEMPLATE_V1.tasks
  .filter((t) => t.optionalTrack)
  .map((t) => t.key);

export const POST_TRAINING_TOTAL_MINUTES = TEMPLATE_V1.tasks
  .filter((t) => t.optionalTrack)
  .reduce((sum, t) => sum + t.minutes, 0);

/** Sanity invariants enforced by tests (see tests/unit/templateV1.test.ts). */
export const TEMPLATE_TOTAL_REQUIRED_MINUTES = TEMPLATE_V1.tasks
  .filter((t) => !t.optionalTrack)
  .reduce((sum, t) => sum + t.minutes, 0);
