/**
 * Aggregated deliverable definitions for the curriculum.
 *
 * Each weekNN.ts module carries:
 * - per-task deliverables for the template-generated tasks of that week
 *   (week 1's handcrafted tasks carry theirs inline in tasks/week01.ts);
 * - the week-level deliverable rollup shown in the Plan view;
 * - the task keys where completing requires evidence (tiered enforcement).
 *
 * A future full weekNN.ts execution rewrite absorbs its deliverables module.
 */

import type { TaskDeliverable, WeekDeliverable } from "../../schemas";
import {
  WEEK_01_EVIDENCE_REQUIRED_TASK_KEYS,
  WEEK_01_TASK_DELIVERABLES,
  WEEK_01_WEEK_DELIVERABLES,
} from "./week01";
import {
  WEEK_02_EVIDENCE_REQUIRED_TASK_KEYS,
  WEEK_02_TASK_DELIVERABLES,
  WEEK_02_WEEK_DELIVERABLES,
} from "./week02";
import {
  WEEK_03_EVIDENCE_REQUIRED_TASK_KEYS,
  WEEK_03_TASK_DELIVERABLES,
  WEEK_03_WEEK_DELIVERABLES,
} from "./week03";
import {
  WEEK_04_EVIDENCE_REQUIRED_TASK_KEYS,
  WEEK_04_TASK_DELIVERABLES,
  WEEK_04_WEEK_DELIVERABLES,
} from "./week04";
import {
  WEEK_05_EVIDENCE_REQUIRED_TASK_KEYS,
  WEEK_05_TASK_DELIVERABLES,
  WEEK_05_WEEK_DELIVERABLES,
} from "./week05";
import {
  WEEK_06_EVIDENCE_REQUIRED_TASK_KEYS,
  WEEK_06_TASK_DELIVERABLES,
  WEEK_06_WEEK_DELIVERABLES,
} from "./week06";
import {
  WEEK_07_EVIDENCE_REQUIRED_TASK_KEYS,
  WEEK_07_TASK_DELIVERABLES,
  WEEK_07_WEEK_DELIVERABLES,
} from "./week07";
import {
  WEEK_08_EVIDENCE_REQUIRED_TASK_KEYS,
  WEEK_08_TASK_DELIVERABLES,
  WEEK_08_WEEK_DELIVERABLES,
} from "./week08";
import {
  WEEK_09_EVIDENCE_REQUIRED_TASK_KEYS,
  WEEK_09_TASK_DELIVERABLES,
  WEEK_09_WEEK_DELIVERABLES,
} from "./week09";
import {
  WEEK_10_EVIDENCE_REQUIRED_TASK_KEYS,
  WEEK_10_TASK_DELIVERABLES,
  WEEK_10_WEEK_DELIVERABLES,
} from "./week10";
import {
  WEEK_11_EVIDENCE_REQUIRED_TASK_KEYS,
  WEEK_11_TASK_DELIVERABLES,
  WEEK_11_WEEK_DELIVERABLES,
} from "./week11";
import {
  WEEK_12_EVIDENCE_REQUIRED_TASK_KEYS,
  WEEK_12_TASK_DELIVERABLES,
  WEEK_12_WEEK_DELIVERABLES,
} from "./week12";
import {
  WEEK_13_EVIDENCE_REQUIRED_TASK_KEYS,
  WEEK_13_TASK_DELIVERABLES,
  WEEK_13_WEEK_DELIVERABLES,
} from "./week13";
import {
  WEEK_14_EVIDENCE_REQUIRED_TASK_KEYS,
  WEEK_14_TASK_DELIVERABLES,
  WEEK_14_WEEK_DELIVERABLES,
} from "./week14";

interface WeekDeliverableModule {
  TASK_DELIVERABLES: Record<string, TaskDeliverable[]>;
  EVIDENCE_REQUIRED_TASK_KEYS: string[];
  WEEK_DELIVERABLES: WeekDeliverable[];
}

const MODULES: WeekDeliverableModule[] = [
  {
    TASK_DELIVERABLES: WEEK_01_TASK_DELIVERABLES,
    EVIDENCE_REQUIRED_TASK_KEYS: WEEK_01_EVIDENCE_REQUIRED_TASK_KEYS,
    WEEK_DELIVERABLES: WEEK_01_WEEK_DELIVERABLES,
  },
  {
    TASK_DELIVERABLES: WEEK_02_TASK_DELIVERABLES,
    EVIDENCE_REQUIRED_TASK_KEYS: WEEK_02_EVIDENCE_REQUIRED_TASK_KEYS,
    WEEK_DELIVERABLES: WEEK_02_WEEK_DELIVERABLES,
  },
  {
    TASK_DELIVERABLES: WEEK_03_TASK_DELIVERABLES,
    EVIDENCE_REQUIRED_TASK_KEYS: WEEK_03_EVIDENCE_REQUIRED_TASK_KEYS,
    WEEK_DELIVERABLES: WEEK_03_WEEK_DELIVERABLES,
  },
  {
    TASK_DELIVERABLES: WEEK_04_TASK_DELIVERABLES,
    EVIDENCE_REQUIRED_TASK_KEYS: WEEK_04_EVIDENCE_REQUIRED_TASK_KEYS,
    WEEK_DELIVERABLES: WEEK_04_WEEK_DELIVERABLES,
  },
  {
    TASK_DELIVERABLES: WEEK_05_TASK_DELIVERABLES,
    EVIDENCE_REQUIRED_TASK_KEYS: WEEK_05_EVIDENCE_REQUIRED_TASK_KEYS,
    WEEK_DELIVERABLES: WEEK_05_WEEK_DELIVERABLES,
  },
  {
    TASK_DELIVERABLES: WEEK_06_TASK_DELIVERABLES,
    EVIDENCE_REQUIRED_TASK_KEYS: WEEK_06_EVIDENCE_REQUIRED_TASK_KEYS,
    WEEK_DELIVERABLES: WEEK_06_WEEK_DELIVERABLES,
  },
  {
    TASK_DELIVERABLES: WEEK_07_TASK_DELIVERABLES,
    EVIDENCE_REQUIRED_TASK_KEYS: WEEK_07_EVIDENCE_REQUIRED_TASK_KEYS,
    WEEK_DELIVERABLES: WEEK_07_WEEK_DELIVERABLES,
  },
  {
    TASK_DELIVERABLES: WEEK_08_TASK_DELIVERABLES,
    EVIDENCE_REQUIRED_TASK_KEYS: WEEK_08_EVIDENCE_REQUIRED_TASK_KEYS,
    WEEK_DELIVERABLES: WEEK_08_WEEK_DELIVERABLES,
  },
  {
    TASK_DELIVERABLES: WEEK_09_TASK_DELIVERABLES,
    EVIDENCE_REQUIRED_TASK_KEYS: WEEK_09_EVIDENCE_REQUIRED_TASK_KEYS,
    WEEK_DELIVERABLES: WEEK_09_WEEK_DELIVERABLES,
  },
  {
    TASK_DELIVERABLES: WEEK_10_TASK_DELIVERABLES,
    EVIDENCE_REQUIRED_TASK_KEYS: WEEK_10_EVIDENCE_REQUIRED_TASK_KEYS,
    WEEK_DELIVERABLES: WEEK_10_WEEK_DELIVERABLES,
  },
  {
    TASK_DELIVERABLES: WEEK_11_TASK_DELIVERABLES,
    EVIDENCE_REQUIRED_TASK_KEYS: WEEK_11_EVIDENCE_REQUIRED_TASK_KEYS,
    WEEK_DELIVERABLES: WEEK_11_WEEK_DELIVERABLES,
  },
  {
    TASK_DELIVERABLES: WEEK_12_TASK_DELIVERABLES,
    EVIDENCE_REQUIRED_TASK_KEYS: WEEK_12_EVIDENCE_REQUIRED_TASK_KEYS,
    WEEK_DELIVERABLES: WEEK_12_WEEK_DELIVERABLES,
  },
  {
    TASK_DELIVERABLES: WEEK_13_TASK_DELIVERABLES,
    EVIDENCE_REQUIRED_TASK_KEYS: WEEK_13_EVIDENCE_REQUIRED_TASK_KEYS,
    WEEK_DELIVERABLES: WEEK_13_WEEK_DELIVERABLES,
  },
  {
    TASK_DELIVERABLES: WEEK_14_TASK_DELIVERABLES,
    EVIDENCE_REQUIRED_TASK_KEYS: WEEK_14_EVIDENCE_REQUIRED_TASK_KEYS,
    WEEK_DELIVERABLES: WEEK_14_WEEK_DELIVERABLES,
  },
];

/** Per-task deliverable overrides keyed by canonical template task key. */
export const TASK_DELIVERABLES: Record<string, TaskDeliverable[]> = Object.assign(
  {},
  ...MODULES.map((module) => module.TASK_DELIVERABLES),
);

/** Task keys where completion requires evidence (HTTPS link or note). */
export const EVIDENCE_REQUIRED_TASK_KEYS: ReadonlySet<string> = new Set(
  MODULES.flatMap((module) => module.EVIDENCE_REQUIRED_TASK_KEYS),
);

/** Week-level deliverables keyed by week number. */
export const WEEK_DELIVERABLES: Record<number, WeekDeliverable[]> = Object.fromEntries(
  MODULES.map((module, index) => [index + 1, module.WEEK_DELIVERABLES]),
);
